### ISSUE TITLE
Categories ids

### ISSUE THREAD

**Issue by MaximKiselev** [asaladino/simple-craig#1]
Hi, man. I have a small question. How did you extract categories ids. Are they right - primary key on cl?
Thank u.

**Comment by asaladino** [comment]
I'm pretty sure I just scrapped the form.

**Comment by asaladino** [comment]
I guess I hard coded them to start and planned to use a server-side webservice to scrape them and return json. But we stopped development before we got to that point.

https://github.com/asaladino/simple-craig/blob/master/SimpleCraig/CategoryRepository.m

**Comment by MaximKiselev** [comment]
Heh, thanks. Yes, i saw that. Some forms returned non correct responses. I tried to get full categories trees with  all fields. Many dirty data...
